env:
  browser: true
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - files: ./src/**/*spec.ts*
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
  - files: ./src/**/*.tsx
    rules:
      '@typescript-eslint/no-unused-vars': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/typedef': 'off'
  unicorn/prevent-abbreviations: 'off'
